[book]
title = "Moxi 的个人网站"
authors = ["Moxi"]
description = "记录一生一芯学习、开发实践、工具获取与随笔。"
language = "zh-CN"
src = "src"

[build]
build-dir = "book"
create-missing = false

[output.html]
theme = "theme"
default-theme = "light"
preferred-dark-theme = "navy"
no-section-label = true
git-repository-url = "https://github.com/moxi-6/moxi-6.github.io"
site-url = "/"
input-404 = "404.md"

[output.html.search]
enable = false
